// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnp3SY9XEyF-le5q_Tcv-7Le2qqvtz0ZM',
    appId: '1:648540980109:web:97fbe182c59bb2641ab3c4',
    messagingSenderId: '648540980109',
    projectId: 'sports-booking-app-1d7e5',
    authDomain: 'sports-booking-app-1d7e5.firebaseapp.com',
    storageBucket: 'sports-booking-app-1d7e5.firebasestorage.app',
    measurementId: 'G-VL4MCP1PZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnp3SY9XEyF-le5q_Tcv-7Le2qqvtz0ZM',
    appId: '1:648540980109:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '648540980109',
    projectId: 'sports-booking-app-1d7e5',
    storageBucket: 'sports-booking-app-1d7e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnp3SY9XEyF-le5q_Tcv-7Le2qqvtz0ZM',
    appId: '1:648540980109:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '648540980109',
    projectId: 'sports-booking-app-1d7e5',
    storageBucket: 'sports-booking-app-1d7e5.firebasestorage.app',
    iosBundleId: 'com.allcourt.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnp3SY9XEyF-le5q_Tcv-7Le2qqvtz0ZM',
    appId: '1:648540980109:ios:YOUR_MACOS_APP_ID',
    messagingSenderId: '648540980109',
    projectId: 'sports-booking-app-1d7e5',
    storageBucket: 'sports-booking-app-1d7e5.firebasestorage.app',
    iosBundleId: 'com.allcourt.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnp3SY9XEyF-le5q_Tcv-7Le2qqvtz0ZM',
    appId: '1:648540980109:web:YOUR_WINDOWS_APP_ID',
    messagingSenderId: '648540980109',
    projectId: 'sports-booking-app-1d7e5',
    authDomain: 'sports-booking-app-1d7e5.firebaseapp.com',
    storageBucket: 'sports-booking-app-1d7e5.firebasestorage.app',
  );
}